name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  hello-world:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Hello World
      run: echo "Hello, World!"
